/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Report,
  ReportDraftOutput,
  Study
} from './model';

import {
  getCreateReportResponseMock,
  getGetReportResponseMock,
  getGetStudyResponseMock,
  getListStudiesResponseMock,
  getResetDemoResponseMock,
  getSaveDraftResponseMock
} from './poc.faker';

export { getListStudiesResponseMock, getGetStudyResponseMock, getCreateReportResponseMock, getGetReportResponseMock, getSaveDraftResponseMock, getResetDemoResponseMock } from './poc.faker';


export const getListStudiesMockHandler = (overrideResponse?: Study[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Study[]> | Study[]), options?: RequestHandlerOptions) => {
  return http.get('*/studies', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListStudiesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetStudyMockHandler = (overrideResponse?: Study | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Study> | Study), options?: RequestHandlerOptions) => {
  return http.get('*/studies/:studyId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetStudyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateReportMockHandler = (overrideResponse?: Report | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Report> | Report), options?: RequestHandlerOptions) => {
  return http.post('*/studies/:studyId/report', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateReportResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetReportMockHandler = (overrideResponse?: Report | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Report> | Report), options?: RequestHandlerOptions) => {
  return http.get('*/studies/:studyId/report', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReportResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSaveDraftMockHandler = (overrideResponse?: ReportDraftOutput | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ReportDraftOutput> | ReportDraftOutput), options?: RequestHandlerOptions) => {
  return http.put('*/studies/:studyId/report/draft', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSaveDraftResponseMock(),
      { status: 200
      })
  }, options)
}

export const getResetDemoMockHandler = (overrideResponse?: Study[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Study[]> | Study[]), options?: RequestHandlerOptions) => {
  return http.post('*/reset', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getResetDemoResponseMock(),
      { status: 200
      })
  }, options)
}
export const getRadiologyStudiesPoCMock = () => [
  getListStudiesMockHandler(),
  getGetStudyMockHandler(),
  getCreateReportMockHandler(),
  getGetReportMockHandler(),
  getSaveDraftMockHandler(),
  getResetDemoMockHandler()
]
