/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorOut,
  HTTPValidationError,
  ListStudiesParams,
  Report,
  ReportDraftInput,
  ReportDraftOutput,
  ReportIn,
  Study
} from './model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listStudiesResponse200 = {
  data: Study[]
  status: 200
}

export type listStudiesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listStudiesResponseSuccess = (listStudiesResponse200) & {
  headers: Headers;
};
export type listStudiesResponseError = (listStudiesResponse422) & {
  headers: Headers;
};

export type listStudiesResponse = (listStudiesResponseSuccess | listStudiesResponseError)

export const getListStudiesUrl = (params?: ListStudiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/studies?${stringifiedParams}` : `/api/studies`
}

/**
 * List studies, optionally filtered by modality.
 *
 * The `modality` query param is a `str, Enum`, so the generated TS type is a
 * literal union — passing `"PET"` from the frontend is a compile error.
 * @summary List Studies
 */
export const listStudies = async (params?: ListStudiesParams, options?: RequestInit): Promise<listStudiesResponse> => {

  const res = await fetch(getListStudiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listStudiesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listStudiesResponse
}





export const getListStudiesQueryKey = (params?: ListStudiesParams,) => {
    return [
    `/api/studies`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStudiesQueryOptions = <TData = Awaited<ReturnType<typeof listStudies>>, TError = HTTPValidationError>(params?: ListStudiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStudiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStudies>>> = ({ signal }) => listStudies(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStudiesQueryResult = NonNullable<Awaited<ReturnType<typeof listStudies>>>
export type ListStudiesQueryError = HTTPValidationError


export function useListStudies<TData = Awaited<ReturnType<typeof listStudies>>, TError = HTTPValidationError>(
 params: undefined |  ListStudiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStudies>>,
          TError,
          Awaited<ReturnType<typeof listStudies>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStudies<TData = Awaited<ReturnType<typeof listStudies>>, TError = HTTPValidationError>(
 params?: ListStudiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStudies>>,
          TError,
          Awaited<ReturnType<typeof listStudies>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStudies<TData = Awaited<ReturnType<typeof listStudies>>, TError = HTTPValidationError>(
 params?: ListStudiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Studies
 */

export function useListStudies<TData = Awaited<ReturnType<typeof listStudies>>, TError = HTTPValidationError>(
 params?: ListStudiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudies>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStudiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getStudyResponse200 = {
  data: Study
  status: 200
}

export type getStudyResponse404 = {
  data: ErrorOut
  status: 404
}

export type getStudyResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getStudyResponseSuccess = (getStudyResponse200) & {
  headers: Headers;
};
export type getStudyResponseError = (getStudyResponse404 | getStudyResponse422) & {
  headers: Headers;
};

export type getStudyResponse = (getStudyResponseSuccess | getStudyResponseError)

export const getGetStudyUrl = (studyId: string,) => {




  return `/api/studies/${studyId}`
}

/**
 * @summary Get Study
 */
export const getStudy = async (studyId: string, options?: RequestInit): Promise<getStudyResponse> => {

  const res = await fetch(getGetStudyUrl(studyId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getStudyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStudyResponse
}





export const getGetStudyQueryKey = (studyId: string,) => {
    return [
    `/api/studies/${studyId}`
    ] as const;
    }


export const getGetStudyQueryOptions = <TData = Awaited<ReturnType<typeof getStudy>>, TError = ErrorOut | HTTPValidationError>(studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudyQueryKey(studyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudy>>> = ({ signal }) => getStudy(studyId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: studyId !== null && studyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudyQueryResult = NonNullable<Awaited<ReturnType<typeof getStudy>>>
export type GetStudyQueryError = ErrorOut | HTTPValidationError


export function useGetStudy<TData = Awaited<ReturnType<typeof getStudy>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudy>>,
          TError,
          Awaited<ReturnType<typeof getStudy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudy<TData = Awaited<ReturnType<typeof getStudy>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudy>>,
          TError,
          Awaited<ReturnType<typeof getStudy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudy<TData = Awaited<ReturnType<typeof getStudy>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Study
 */

export function useGetStudy<TData = Awaited<ReturnType<typeof getStudy>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudyQueryOptions(studyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type createReportResponse201 = {
  data: Report
  status: 201
}

export type createReportResponse404 = {
  data: ErrorOut
  status: 404
}

export type createReportResponse409 = {
  data: ErrorOut
  status: 409
}

export type createReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createReportResponseSuccess = (createReportResponse201) & {
  headers: Headers;
};
export type createReportResponseError = (createReportResponse404 | createReportResponse409 | createReportResponse422) & {
  headers: Headers;
};

export type createReportResponse = (createReportResponseSuccess | createReportResponseError)

export const getCreateReportUrl = (studyId: string,) => {




  return `/api/studies/${studyId}/report`
}

/**
 * Attach a report to a study.
 *
 * `body` is a Pydantic model, so the TS call site's `body:` argument is
 * checked field by field against it.
 * @summary Create Report
 */
export const createReport = async (studyId: string,
    reportIn: ReportIn, options?: RequestInit): Promise<createReportResponse> => {

  const res = await fetch(getCreateReportUrl(studyId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reportIn)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createReportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createReportResponse
}





export const getCreateReportMutationOptions = <TError = ErrorOut | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{studyId: string;data: ReportIn}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{studyId: string;data: ReportIn}, TContext> => {

const mutationKey = ['createReport'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReport>>, {studyId: string;data: ReportIn}> = (props) => {
          const {studyId,data} = props ?? {};

          return  createReport(studyId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>
    export type CreateReportMutationBody = ReportIn
    export type CreateReportMutationError = ErrorOut | HTTPValidationError

    /**
 * @summary Create Report
 */
export const useCreateReport = <TError = ErrorOut | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{studyId: string;data: ReportIn}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReport>>,
        TError,
        {studyId: string;data: ReportIn},
        TContext
      > => {
      return useMutation(getCreateReportMutationOptions(options), queryClient);
    }

export type getReportResponse200 = {
  data: Report
  status: 200
}

export type getReportResponse404 = {
  data: ErrorOut
  status: 404
}

export type getReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getReportResponseSuccess = (getReportResponse200) & {
  headers: Headers;
};
export type getReportResponseError = (getReportResponse404 | getReportResponse422) & {
  headers: Headers;
};

export type getReportResponse = (getReportResponseSuccess | getReportResponseError)

export const getGetReportUrl = (studyId: string,) => {




  return `/api/studies/${studyId}/report`
}

/**
 * @summary Get Report
 */
export const getReport = async (studyId: string, options?: RequestInit): Promise<getReportResponse> => {

  const res = await fetch(getGetReportUrl(studyId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReportResponse
}





export const getGetReportQueryKey = (studyId: string,) => {
    return [
    `/api/studies/${studyId}/report`
    ] as const;
    }


export const getGetReportQueryOptions = <TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorOut | HTTPValidationError>(studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReportQueryKey(studyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) => getReport(studyId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: studyId !== null && studyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>
export type GetReportQueryError = ErrorOut | HTTPValidationError


export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Report
 */

export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorOut | HTTPValidationError>(
 studyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReportQueryOptions(studyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type saveDraftResponse200 = {
  data: ReportDraftOutput
  status: 200
}

export type saveDraftResponse404 = {
  data: ErrorOut
  status: 404
}

export type saveDraftResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type saveDraftResponseSuccess = (saveDraftResponse200) & {
  headers: Headers;
};
export type saveDraftResponseError = (saveDraftResponse404 | saveDraftResponse422) & {
  headers: Headers;
};

export type saveDraftResponse = (saveDraftResponseSuccess | saveDraftResponseError)

export const getSaveDraftUrl = (studyId: string,) => {




  return `/api/studies/${studyId}/report/draft`
}

/**
 * Autosave a partially-filled report and echo back what was stored.
 *
 * The same model on the way in and on the way out — see GOTCHA #1 in
 * `models.py` for why that combination is what splits the schema.
 * @summary Save Draft
 */
export const saveDraft = async (studyId: string,
    reportDraftInput: ReportDraftInput, options?: RequestInit): Promise<saveDraftResponse> => {

  const res = await fetch(getSaveDraftUrl(studyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reportDraftInput)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: saveDraftResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as saveDraftResponse
}





export const getSaveDraftMutationOptions = <TError = ErrorOut | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{studyId: string;data: ReportDraftInput}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{studyId: string;data: ReportDraftInput}, TContext> => {

const mutationKey = ['saveDraft'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveDraft>>, {studyId: string;data: ReportDraftInput}> = (props) => {
          const {studyId,data} = props ?? {};

          return  saveDraft(studyId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveDraftMutationResult = NonNullable<Awaited<ReturnType<typeof saveDraft>>>
    export type SaveDraftMutationBody = ReportDraftInput
    export type SaveDraftMutationError = ErrorOut | HTTPValidationError

    /**
 * @summary Save Draft
 */
export const useSaveDraft = <TError = ErrorOut | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveDraft>>, TError,{studyId: string;data: ReportDraftInput}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveDraft>>,
        TError,
        {studyId: string;data: ReportDraftInput},
        TContext
      > => {
      return useMutation(getSaveDraftMutationOptions(options), queryClient);
    }

export type resetDemoResponse200 = {
  data: Study[]
  status: 200
}

export type resetDemoResponseSuccess = (resetDemoResponse200) & {
  headers: Headers;
};
;

export type resetDemoResponse = (resetDemoResponseSuccess)

export const getResetDemoUrl = () => {




  return `/api/reset`
}

/**
 * Restore seed data so the demo can be replayed.
 * @summary Reset Demo
 */
export const resetDemo = async ( options?: RequestInit): Promise<resetDemoResponse> => {

  const res = await fetch(getResetDemoUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resetDemoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resetDemoResponse
}





export const getResetDemoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetDemo>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof resetDemo>>, TError,void, TContext> => {

const mutationKey = ['resetDemo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetDemo>>, void> = () => {


          return  resetDemo(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetDemoMutationResult = NonNullable<Awaited<ReturnType<typeof resetDemo>>>

    export type ResetDemoMutationError = unknown

    /**
 * @summary Reset Demo
 */
export const useResetDemo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetDemo>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetDemo>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getResetDemoMutationOptions(options), queryClient);
    }

