/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  Modality,
  StudyStatus
} from './model';
import type {
  Report,
  ReportDraftOutput,
  Study
} from './model';


export const getListStudiesResponseMock = (): Study[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), patient_name: faker.string.alpha({length: {min: 10, max: 20}}), modality: faker.helpers.arrayElement(Object.values(Modality)), body_part: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(StudyStatus)), acquired_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getGetStudyResponseMock = (overrideResponse: Partial<Extract<Study, object>> = {}): Study => ({id: faker.string.alpha({length: {min: 10, max: 20}}), patient_name: faker.string.alpha({length: {min: 10, max: 20}}), modality: faker.helpers.arrayElement(Object.values(Modality)), body_part: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(StudyStatus)), acquired_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getCreateReportResponseMock = (overrideResponse: Partial<Extract<Report, object>> = {}): Report => ({study_id: faker.string.alpha({length: {min: 10, max: 20}}), findings: faker.string.alpha({length: {min: 10, max: 20}}), impression: faker.string.alpha({length: {min: 10, max: 20}}), critical: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetReportResponseMock = (overrideResponse: Partial<Extract<Report, object>> = {}): Report => ({study_id: faker.string.alpha({length: {min: 10, max: 20}}), findings: faker.string.alpha({length: {min: 10, max: 20}}), impression: faker.string.alpha({length: {min: 10, max: 20}}), critical: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getSaveDraftResponseMock = (overrideResponse: Partial<Extract<ReportDraftOutput, object>> = {}): ReportDraftOutput => ({findings: faker.string.alpha({length: {min: 10, max: 20}}), impression: faker.string.alpha({length: {min: 10, max: 20}}), critical: faker.datatype.boolean(), is_complete: faker.datatype.boolean(), ...overrideResponse})

export const getResetDemoResponseMock = (): Study[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), patient_name: faker.string.alpha({length: {min: 10, max: 20}}), modality: faker.helpers.arrayElement(Object.values(Modality)), body_part: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(StudyStatus)), acquired_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

