/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Studies
         * @description List studies, optionally filtered by modality.
         *
         *     The `modality` query param is a `str, Enum`, so the generated TS type is a
         *     literal union — passing `"PET"` from the frontend is a compile error.
         */
        get: operations["listStudies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study */
        get: operations["getStudy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{study_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["getReport"];
        put?: never;
        /**
         * Create Report
         * @description Attach a report to a study.
         *
         *     `body` is a Pydantic model, so the TS call site's `body:` argument is
         *     checked field by field against it.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{study_id}/report/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Draft
         * @description Autosave a partially-filled report and echo back what was stored.
         *
         *     The same model on the way in and on the way out — see GOTCHA #1 in
         *     `models.py` for why that combination is what splits the schema.
         */
        put: operations["saveDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Restore seed data so the demo can be replayed.
         */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorOut
         * @description GOTCHA #5 — declared per-route in ``responses=`` so the TS error branch
         *     is narrowed instead of falling back to an untyped blob.
         */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Modality
         * @description GOTCHA #4 — inheriting ``str`` makes this a string literal union in TS.
         *
         *     Without the ``str`` base these land as opaque integers and the frontend
         *     ``<select>`` loses all meaning.
         * @enum {string}
         */
        Modality: "CT" | "MR" | "XR" | "US";
        /** Report */
        Report: {
            /** Study Id */
            study_id: string;
            /** Findings */
            findings: string;
            /** Impression */
            impression: string;
            /**
             * Critical
             * @default false
             */
            critical: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportDraft
         * @description An autosaved, partially-filled report — sent in, echoed back.
         *
         *     GOTCHA #1 — and the PoC's one correction to the source doc.
         *
         *     The doc says a model with defaults splits into `FooInput`/`FooOutput`, and
         *     that `separate_input_output_schemas=False` collapses it. On FastAPI 0.141 +
         *     Pydantic 2.13, **neither half of that is still true**:
         *
         *     * A plain default no longer splits anything. Pydantic 2.13 emits identical
         *       validation and serialization schemas for `ReportIn` above, so there is
         *       only ever one `ReportIn`.
         *     * What splits a model now is a genuine divergence between those two
         *       schemas — here the `is_complete` computed field, which the server derives
         *       and the client must never send.
         *     * And that split **ignores the flag**. See `fastapi/_compat/v2.py`:
         *       `separate_input_output_schemas or _has_computed_fields(field)` — a
         *       computed field forces separation either way. `just gotchas` proves it by
         *       flipping the flag and showing the spec does not change.
         *
         *     The fix is therefore not a flag but a modelling decision: let the split
         *     stand and treat `-Input`/`-Output` as the two genuinely different shapes
         *     they are, or drop the computed field and derive it client-side. This PoC
         *     lets it stand — see `docs/GOTCHAS.md`.
         */
        "ReportDraft-Input": {
            /**
             * Findings
             * @default
             */
            findings: string;
            /**
             * Impression
             * @default
             */
            impression: string;
            /**
             * Critical
             * @default false
             */
            critical: boolean;
        };
        /**
         * ReportDraft
         * @description An autosaved, partially-filled report — sent in, echoed back.
         *
         *     GOTCHA #1 — and the PoC's one correction to the source doc.
         *
         *     The doc says a model with defaults splits into `FooInput`/`FooOutput`, and
         *     that `separate_input_output_schemas=False` collapses it. On FastAPI 0.141 +
         *     Pydantic 2.13, **neither half of that is still true**:
         *
         *     * A plain default no longer splits anything. Pydantic 2.13 emits identical
         *       validation and serialization schemas for `ReportIn` above, so there is
         *       only ever one `ReportIn`.
         *     * What splits a model now is a genuine divergence between those two
         *       schemas — here the `is_complete` computed field, which the server derives
         *       and the client must never send.
         *     * And that split **ignores the flag**. See `fastapi/_compat/v2.py`:
         *       `separate_input_output_schemas or _has_computed_fields(field)` — a
         *       computed field forces separation either way. `just gotchas` proves it by
         *       flipping the flag and showing the spec does not change.
         *
         *     The fix is therefore not a flag but a modelling decision: let the split
         *     stand and treat `-Input`/`-Output` as the two genuinely different shapes
         *     they are, or drop the computed field and derive it client-side. This PoC
         *     lets it stand — see `docs/GOTCHAS.md`.
         */
        "ReportDraft-Output": {
            /**
             * Findings
             * @default
             */
            findings: string;
            /**
             * Impression
             * @default
             */
            impression: string;
            /**
             * Critical
             * @default false
             */
            critical: boolean;
            /**
             * Is Complete
             * @description Server-derived: output-only, never part of the request.
             */
            readonly is_complete: boolean;
        };
        /**
         * ReportIn
         * @description The request body. Type-checked against the TS call site.
         */
        ReportIn: {
            /**
             * Findings
             * @description What was seen.
             */
            findings: string;
            /**
             * Impression
             * @description What it means.
             */
            impression: string;
            /**
             * Critical
             * @default false
             */
            critical: boolean;
        };
        /** Study */
        Study: {
            /** Id */
            id: string;
            /** Patient Name */
            patient_name: string;
            modality: components["schemas"]["Modality"];
            /** Body Part */
            body_part: string;
            status: components["schemas"]["StudyStatus"];
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
        };
        /**
         * StudyStatus
         * @enum {string}
         */
        StudyStatus: "pending" | "reported";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStudies: {
        parameters: {
            query?: {
                /** @description Filter by imaging modality. */
                modality?: components["schemas"]["Modality"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Study"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStudy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Study"];
                };
            };
            /** @description No such study. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description No such study. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description No such study. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Study is already reported. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saveDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportDraft-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDraft-Output"];
                };
            };
            /** @description No such study. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resetDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Study"][];
                };
            };
        };
    };
}
