/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

/**
 * GOTCHA #5 — declared per-route in ``responses=`` so the TS error branch
 * is narrowed instead of falling back to an untyped blob.
 */
export interface ErrorOut {
  code: string;
  message: string;
}
