/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */
import type { Modality } from './modality';

export type ListStudiesParams = {
/**
 * Filter by imaging modality.
 */
modality?: Modality | null;
};
