/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

/**
 * GOTCHA #4 — inheriting ``str`` makes this a string literal union in TS.
 *
 * Without the ``str`` base these land as opaque integers and the frontend
 * ``<select>`` loses all meaning.
 */
export type Modality = typeof Modality[keyof typeof Modality];


export const Modality = {
  CT: 'CT',
  MR: 'MR',
  XR: 'XR',
  US: 'US',
} as const;
