/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

/**
 * An autosaved, partially-filled report — sent in, echoed back.
 *
 * GOTCHA #1 — and the PoC's one correction to the source doc.
 *
 * The doc says a model with defaults splits into `FooInput`/`FooOutput`, and
 * that `separate_input_output_schemas=False` collapses it. On FastAPI 0.141 +
 * Pydantic 2.13, **neither half of that is still true**:
 *
 * * A plain default no longer splits anything. Pydantic 2.13 emits identical
 *   validation and serialization schemas for `ReportIn` above, so there is
 *   only ever one `ReportIn`.
 * * What splits a model now is a genuine divergence between those two
 *   schemas — here the `is_complete` computed field, which the server derives
 *   and the client must never send.
 * * And that split **ignores the flag**. See `fastapi/_compat/v2.py`:
 *   `separate_input_output_schemas or _has_computed_fields(field)` — a
 *   computed field forces separation either way. `just gotchas` proves it by
 *   flipping the flag and showing the spec does not change.
 *
 * The fix is therefore not a flag but a modelling decision: let the split
 * stand and treat `-Input`/`-Output` as the two genuinely different shapes
 * they are, or drop the computed field and derive it client-side. This PoC
 * lets it stand — see `docs/GOTCHAS.md`.
 */
export interface ReportDraftOutput {
  findings?: string;
  impression?: string;
  critical?: boolean;
  /** Server-derived: output-only, never part of the request. */
  readonly is_complete: boolean;
}
