/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

export interface Report {
  study_id: string;
  findings: string;
  impression: string;
  critical?: boolean;
  created_at: string;
}
