/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

/**
 * The request body. Type-checked against the TS call site.
 */
export interface ReportIn {
  /**
     * What was seen.
     * @minLength 1
     */
  findings: string;
  /**
     * What it means.
     * @minLength 1
     */
  impression: string;
  critical?: boolean;
}
