/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */
import type { Modality } from './modality';
import type { StudyStatus } from './studyStatus';

export interface Study {
  id: string;
  patient_name: string;
  modality: Modality;
  body_part: string;
  status: StudyStatus;
  acquired_at: string;
}
