/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Radiology Studies PoC
 * OpenAPI spec version: 0.1.0
 */

export type StudyStatus = typeof StudyStatus[keyof typeof StudyStatus];


export const StudyStatus = {
  pending: 'pending',
  reported: 'reported',
} as const;
